spring:
    datasource:
        //driverClassName: org.h2.Driver
        driverClassName: org.postgresql.Driver
        //url: jdbc:h2:file:C:\environment\tmp\testdb
        url: jdbc:postgresql://localhost:5432/student
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
    http:
      multipart:
        max-file-size: 1MB
        max-request-size: 10MB
        
security:  
  basic: 
    enabled: false
    
server:
  context-path: /app
    
//    user:
//      name: moriya
//      password: moriya